// Code generated by sqlgen. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/jmoiron/sqlx"
)

// UserModel represents a user model.
type UserModel struct {
	db *sqlx.DB
}

// User represents a user struct data.
type User struct {
	Id         uint64    `db:"id" json:"id"`
	Name       string    `db:"name" json:"name"`
	Password   string    `db:"password" json:"password"`
	Mobile     string    `db:"mobile" json:"mobile"`
	Gender     string    `db:"gender" json:"gender"`
	Nickname   string    `db:"nickname" json:"nickname"`
	Type       int8      `db:"type" json:"type"`
	CreateTime time.Time `db:"create_time" json:"createTime"`
	UpdateTime time.Time `db:"update_time" json:"updateTime"`
}

// NewUserModel creates a new user model.
func NewUserModel(db *sqlx.DB) *UserModel {
	return &UserModel{
		db: db,
	}
}

// Create creates  user data.
func (m *UserModel) Create(ctx context.Context, data ...*User) (err error) {
	if len(data) == 0 {
		return fmt.Errorf("data is empty")
	}

	var stmt *sql.Stmt
	stmt, err = m.db.PrepareContext(ctx, "INSERT INTO user (`name`, `password`, `mobile`, `gender`, `nickname`, `type`, `create_time`, `update_time`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)")
	if err != nil {
		return
	}
	defer func() {
		err = stmt.Close()
	}()
	for _, v := range data {
		result, err := stmt.ExecContext(ctx, v.Name, v.Password, v.Mobile, v.Gender, v.Nickname, v.Type, v.CreateTime, v.UpdateTime)
		if err != nil {
			return err
		}

		id, err := result.LastInsertId()
		if err != nil {
			return err
		}

		v.Id = uint64(id)
	}
	return
}
